/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitsIndexRouteImport } from './routes/kits.index'
import { Route as KitsKitIdRouteImport } from './routes/kits.$kitId'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsIndexRoute = KitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitsRoute,
} as any)
const KitsKitIdRoute = KitsKitIdRouteImport.update({
  id: '/$kitId',
  path: '/$kitId',
  getParentRoute: () => KitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kits': typeof KitsRouteWithChildren
  '/tutorials': typeof TutorialsRoute
  '/kits/$kitId': typeof KitsKitIdRoute
  '/kits/': typeof KitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tutorials': typeof TutorialsRoute
  '/kits/$kitId': typeof KitsKitIdRoute
  '/kits': typeof KitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kits': typeof KitsRouteWithChildren
  '/tutorials': typeof TutorialsRoute
  '/kits/$kitId': typeof KitsKitIdRoute
  '/kits/': typeof KitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/kits' | '/tutorials' | '/kits/$kitId' | '/kits/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/tutorials' | '/kits/$kitId' | '/kits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/kits'
    | '/tutorials'
    | '/kits/$kitId'
    | '/kits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  KitsRoute: typeof KitsRouteWithChildren
  TutorialsRoute: typeof TutorialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits/': {
      id: '/kits/'
      path: '/'
      fullPath: '/kits/'
      preLoaderRoute: typeof KitsIndexRouteImport
      parentRoute: typeof KitsRoute
    }
    '/kits/$kitId': {
      id: '/kits/$kitId'
      path: '/$kitId'
      fullPath: '/kits/$kitId'
      preLoaderRoute: typeof KitsKitIdRouteImport
      parentRoute: typeof KitsRoute
    }
  }
}

interface KitsRouteChildren {
  KitsKitIdRoute: typeof KitsKitIdRoute
  KitsIndexRoute: typeof KitsIndexRoute
}

const KitsRouteChildren: KitsRouteChildren = {
  KitsKitIdRoute: KitsKitIdRoute,
  KitsIndexRoute: KitsIndexRoute,
}

const KitsRouteWithChildren = KitsRoute._addFileChildren(KitsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  KitsRoute: KitsRouteWithChildren,
  TutorialsRoute: TutorialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
